all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
all_joints_names:
- UL(Upper_Lid)
- DL(Down_Lid)
- LL(Left_Lid)
- RL(Right_Lid)
- Top
- Bottom
- Left
- Right
- TR(Top_Right)
- BR(Bottom_Right)
- BL(Bottom_Left)
- TL(Top_Left)
- Centre
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_RF_Mapping_MotionSep6\RF_Mapping_Motion_Elisa95shuffle3.mat
dataset_type: albumentations
decay_steps: 30000
display_iters: 1000
engine: pytorch
global_scale: 0.8
init_weights: C:\Users\kampaimaging\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_RF_Mapping_MotionSep6\Documentation_data-RF_Mapping_Motion_95shuffle3.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 13
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: D:\DeepLabCut_Projects\Elisa\RF_Mapping_Motion-Elisa-2024-09-06
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
